export default {
PRODUCT_LOAD_START:"PRODUCT_LOAD_START",
PRODUCT_LOAD_SUCCESS:"PRODUCT_LOAD_SUCCESS",
PRODUCT_LOAD_ERROR:"PRODUCT_LOAD_ERROR",
SET_CATEGORY:"SET_CATEGORY",
ADD_TO_BASKET:"ADD_TO_BASKET",
REMOVE_FROM_BASKET:"REMOVE_FROM_BASKET",
EMPTY_BASKET:"EMPTY_BASKET",
INC_QUANTITY:"INC_QUANTITY",
DEC_QUANTITY:"DEC_QUANTITY",

};